tablist: true
scoreboard: true
join-quit:
  enabled: true
  join-message: "null"
  first-join: "null"
  leave-message: "null"
prefix:
  enabled: true
  add-prefix-space: true
  add-suffix-space: true
  chat-format: "%prefix% %display_name% §7» %message%"