name: ScorePrefix
version: '${project.version}'
main: de.crazydev22.scoreprefix.ScorePrefix
api-version: '1.20'
load: STARTUP
depend: [LuckPerms, PlaceholderAPI]
authors: [CrazyDev22]

commands:
  sb:
    permission: "scoreprefix.command"
    aliases: ["scoreprefix"]